blank_issues_enabled: false
contact_links:
  - name: Generally curious?
    url: https://github.com/organizations/AutoIt-Community
    about: Feel free to explore the AutoIt-Community organization on GitHub.
